@baseUrl = http://localhost:3000
@token = {{login.response.body.token}}

# ==========================================
# 1. AUTENTICACIÓN (LOGIN)
# ==========================================

# @name login
POST {{baseUrl}}/auth
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}

